# Site Settings
title: Classy Ultimate
email: mskeving@gmail.com
description: >
  Bay Area Blappers
baseurl: "/classyultimate"
url: "http://mskeving.github.io"
twitter_username: classyultimate
facebook_username: classyultimate
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM