# Site Settings
title: Classy Ultimate
email: mskeving@gmail.com
description: >
  Bay Area Blappers
baseurl: ""
url: "http://localhost:4000"
twitter_username: classychains
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM